services:
  berlin-burgersucher:
    build: .
    container_name: berlin-burgersucher
    restart: unless-stopped
    env_file:
      - .env
    # Uncomment below to mount code for live development
    # volumes:
    #   - ./:/app
