services:
  berlin-appointment-finder:
    build: .
    container_name: berlin-appointment-finder
    restart: unless-stopped
    env_file:
      - .env
    user: "appuser"
    read_only: true
    tmpfs:
      - /tmp
    volumes:
      - appointment-finder-bot-data:/app/data/:rw
      # - ./data/:/app/data/:rw
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

volumes:
  appointment-finder-bot-data:
