services:
  berlin-appointment-finder:
    build: .
    container_name: berlin-appointment-finder
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./bot_data.pkl:/app/bot_data.pkl

